# permissions for end users to edit cannalops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cannalop-editor-role
rules:
- apiGroups:
  - v1.com.cannal
  resources:
  - cannalops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.com.cannal
  resources:
  - cannalops/status
  verbs:
  - get
