
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - v1.com.cannal
  resources:
  - cannalops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.com.cannal
  resources:
  - cannalops/finalizers
  verbs:
  - update
- apiGroups:
  - v1.com.cannal
  resources:
  - cannalops/status
  verbs:
  - get
  - patch
  - update
